-- ============================================================
-- Схема Supabase для сайта «Естественные архетипы взаимоотношений»
-- Выполните этот файл целиком в Supabase: SQL Editor -> New query -> Run
-- ============================================================

-- ============================================================
-- 1. ТАБЛИЦЫ
-- ============================================================

-- Профили пользователей (создаются автоматически триггером при регистрации)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  login text not null unique,
  telegram text,
  gender text check (gender in ('male', 'female')),
  orientation text,
  role text not null default 'user' check (role in ('user', 'admin')),
  compatibility_code text unique,
  archetype_scores jsonb,
  active_archetypes jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Справочник архетипов (14 классов: 1.x — мужские, 2.x — женские)
create table if not exists public.archetypes (
  code text primary key,
  name text not null,
  color text,
  chakra integer,
  description text,
  strengths text,
  weaknesses text
);

-- Вопросы теста на архетипы.
-- КАЖДЫЙ вопрос привязан к своему классу (archetype_code):
-- ответ «Да» добавляет 1 балл именно этому архетипу.
create table if not exists public.questions (
  id integer generated by default as identity primary key,
  gender_type text not null check (gender_type in ('male', 'female')),
  text text not null,
  archetype_code text not null references public.archetypes(code),
  order_index integer not null,
  is_active boolean not null default true
);

-- Сырые ответы (журнал прохождений)
create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  session_id text,
  question_id integer not null references public.questions(id),
  value boolean not null,
  created_at timestamptz not null default now()
);

-- Результаты тестов
create table if not exists public.test_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  user_login text not null,
  user_telegram text,
  test_type text not null,
  gender text,
  total_score double precision default 0,
  archetype_result text,
  archetype_name text,
  scores_breakdown jsonb,
  result_text text,
  completed_at timestamptz not null default now()
);

-- Заявки на консультацию
create table if not exists public.consultations (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  name text not null,
  telegram text,
  category text,
  topic text,
  request_text text not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Журнал проверок совместимости
create table if not exists public.couples (
  id bigint generated by default as identity primary key,
  user1_code text not null,
  user2_code text not null,
  compatibility_index text,
  a_count integer default 0,
  p_count integer default 0,
  score double precision default 0,
  interpretation text,
  created_at timestamptz not null default now()
);

-- Конструктор дополнительных тестов (админ-панель)
create table if not exists public.tests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.test_questions (
  id bigint generated by default as identity primary key,
  test_id bigint not null references public.tests(id) on delete cascade,
  text text not null,
  order_index integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.answer_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.test_questions(id) on delete cascade,
  text text not null,
  score double precision not null default 0,
  order_index integer not null,
  is_active boolean not null default true
);

-- Комментарии
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  user_login text not null,
  content text not null,
  target_type text not null default 'general',
  target_id bigint,
  parent_id bigint references public.comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_deleted boolean not null default false
);

create index if not exists idx_questions_gender on public.questions (gender_type, order_index);
create index if not exists idx_test_results_user on public.test_results (user_id);
create index if not exists idx_consultations_status on public.consultations (status);
create index if not exists idx_comments_target on public.comments (target_type, target_id);

-- ============================================================
-- 2. ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ
-- ============================================================

-- Проверка «текущий пользователь — админ» (security definer, чтобы не упереться в RLS)
create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active
  );
$$;

-- Статус архетипа по баллам: A — активный, M — средний, N — неопределённый, P — пассивный
create or replace function public.archetype_status(p_score integer)
returns text
language sql immutable
as $$
  select case
    when p_score >= 4 then 'A'
    when p_score = 3 then 'M'
    when p_score = 2 then 'N'
    else 'P'
  end;
$$;

-- Генерация кода совместимости в формате PSY-YYYYMMDD-XXXXXXXXXXXX
create or replace function public.generate_compatibility_code()
returns text
language sql volatile
as $$
  select 'PSY-' || to_char(now(), 'YYYYMMDD') || '-' ||
         upper(substr(md5(random()::text || clock_timestamp()::text), 1, 12));
$$;

-- Проверка занятости логина (используется до регистрации)
create or replace function public.login_exists(p_login text)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles where lower(login) = lower(trim(p_login))
  );
$$;

-- ============================================================
-- 3. ТРИГГЕР: создание профиля при регистрации
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, login, gender, orientation)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'login'), ''), 'user_' || left(new.id::text, 8)),
    nullif(new.raw_user_meta_data ->> 'gender', ''),
    nullif(new.raw_user_meta_data ->> 'orientation', '')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- 4. ЛОГИКА ТЕСТА: подсчёт баллов по каждому классу-архетипу
-- ============================================================

-- Завершение теста. p_answers: [{"question_id": 1, "value": true}, ...]
-- Каждый ответ «Да» добавляет 1 балл архетипу, к которому привязан вопрос.
-- Балл на архетип ограничен 5. Всегда возвращаются все 7 классов пола.
create or replace function public.complete_test(
  p_gender text,
  p_answers jsonb,
  p_session_id text default null
)
returns jsonb
language plpgsql volatile security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_prefix text;
  v_scores jsonb;
  v_statuses jsonb;
  v_code text;
  v_main_code text;
  v_main_name text;
  v_total integer;
  v_login text;
  v_telegram text;
begin
  if v_user_id is null then
    raise exception 'Требуется авторизация';
  end if;

  if p_gender not in ('male', 'female') then
    raise exception 'Неверный параметр пола';
  end if;

  if p_answers is null or jsonb_typeof(p_answers) <> 'array' or jsonb_array_length(p_answers) = 0 then
    raise exception 'Ответы не переданы';
  end if;

  v_prefix := case when p_gender = 'male' then '1.' else '2.' end;

  -- Журналируем ответы
  insert into public.answers (user_id, session_id, question_id, value)
  select v_user_id, p_session_id, (a ->> 'question_id')::integer, (a ->> 'value')::boolean
  from jsonb_array_elements(p_answers) a
  where (a ->> 'question_id') ~ '^\d+$';

  -- Баллы по каждому классу: считаем «Да» по архетипу вопроса, максимум 5,
  -- отсутствующие классы заполняем нулями
  with ans as (
    select (a ->> 'question_id')::integer as question_id,
           (a ->> 'value')::boolean as value
    from jsonb_array_elements(p_answers) a
    where (a ->> 'question_id') ~ '^\d+$'
  ),
  per_class as (
    select q.archetype_code as code, least(count(*), 5)::integer as score
    from ans
    join public.questions q
      on q.id = ans.question_id
     and q.gender_type = p_gender
     and q.is_active
    where ans.value
    group by q.archetype_code
  ),
  full_set as (
    select a.code, coalesce(pc.score, 0) as score
    from public.archetypes a
    left join per_class pc on pc.code = a.code
    where a.code like v_prefix || '%'
  )
  select jsonb_object_agg(code, score),
         jsonb_object_agg(code, public.archetype_status(score)),
         sum(score)::integer
    into v_scores, v_statuses, v_total
  from full_set;

  -- Ведущий архетип — класс с максимальным баллом
  select fs.key, a.name
    into v_main_code, v_main_name
  from jsonb_each_text(v_scores) fs
  join public.archetypes a on a.code = fs.key
  order by fs.value::integer desc, fs.key
  limit 1;

  -- Обновляем профиль; код совместимости генерируем один раз
  select compatibility_code, login, telegram
    into v_code, v_login, v_telegram
  from public.profiles where id = v_user_id;

  if v_code is null then
    loop
      v_code := public.generate_compatibility_code();
      exit when not exists (select 1 from public.profiles where compatibility_code = v_code);
    end loop;
  end if;

  update public.profiles
     set archetype_scores = v_scores,
         active_archetypes = v_statuses,
         gender = p_gender,
         compatibility_code = v_code
   where id = v_user_id;

  -- Сохраняем запись результата
  insert into public.test_results (
    user_id, user_login, user_telegram, test_type, gender,
    total_score, archetype_result, archetype_name, scores_breakdown, result_text
  ) values (
    v_user_id, v_login, v_telegram, 'archetype', p_gender,
    coalesce(v_total, 0), v_main_code, v_main_name, v_scores,
    'Архетип: ' || coalesce(v_main_name, v_main_code, 'Не определён')
  );

  return jsonb_build_object(
    'session_id', p_session_id,
    'compatibility_code', v_code,
    'scores', v_scores,
    'active_archetypes', v_statuses,
    'archetype_code', v_main_code,
    'archetype_name', v_main_name
  );
end;
$$;

-- Результаты по коду совместимости (доступно всем, у кого есть код)
create or replace function public.get_profile_by_code(p_code text)
returns jsonb
language plpgsql stable security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_archetypes jsonb;
begin
  select * into v_profile
  from public.profiles
  where compatibility_code = trim(p_code);

  if not found or v_profile.archetype_scores is null then
    return null;
  end if;

  select jsonb_agg(item order by (item ->> 'score')::integer desc, item ->> 'code')
    into v_archetypes
  from (
    select jsonb_build_object(
      'code', s.key,
      'name', coalesce(a.name, s.key),
      'score', s.value::integer,
      'status', coalesce(v_profile.active_archetypes ->> s.key, public.archetype_status(s.value::integer)),
      'color', coalesce(a.color, '#999'),
      'chakra', a.chakra,
      'description', coalesce(a.description, ''),
      'strengths', coalesce(a.strengths, ''),
      'weaknesses', coalesce(a.weaknesses, '')
    ) as item
    from jsonb_each_text(v_profile.archetype_scores) s
    left join public.archetypes a on a.code = s.key
  ) t;

  return jsonb_build_object(
    'compatibility_code', v_profile.compatibility_code,
    'gender', v_profile.gender,
    'archetypes', coalesce(v_archetypes, '[]'::jsonb)
  );
end;
$$;

-- Привязка результатов, полученных по коду, к текущему аккаунту
create or replace function public.save_results_to_account(p_code text)
returns jsonb
language plpgsql volatile security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_source public.profiles%rowtype;
begin
  if v_user_id is null then
    raise exception 'Требуется авторизация';
  end if;

  select * into v_source
  from public.profiles
  where compatibility_code = trim(p_code);

  if not found then
    raise exception 'Результаты не найдены';
  end if;

  if v_source.id <> v_user_id then
    -- Код переносится на текущий аккаунт (у источника освобождаем уникальное поле)
    update public.profiles set compatibility_code = null where id = v_source.id;
  end if;

  update public.profiles
     set compatibility_code = v_source.compatibility_code,
         archetype_scores = v_source.archetype_scores,
         active_archetypes = v_source.active_archetypes,
         gender = coalesce(v_source.gender, gender),
         orientation = coalesce(v_source.orientation, orientation)
   where id = v_user_id;

  return jsonb_build_object(
    'success', true,
    'compatibility_code', v_source.compatibility_code,
    'archetype_scores', v_source.archetype_scores
  );
end;
$$;

-- ============================================================
-- 5. СОВМЕСТИМОСТЬ ПАРЫ
-- ============================================================

create or replace function public.check_compatibility(p_code1 text, p_code2 text)
returns jsonb
language plpgsql volatile security definer
set search_path = public
as $$
declare
  complementarity constant jsonb := '{
    "1.1": ["2.7", "2.5"], "1.2": ["2.7", "2.4"], "1.3": ["2.6", "2.3"],
    "1.4": ["2.5", "2.3", "2.4", "2.6"], "1.5": ["2.5", "2.2", "2.1", "2.6"],
    "1.6": ["2.4", "2.2", "2.3", "2.5"], "1.7": ["2.5", "2.7", "2.4"],
    "2.1": ["1.5", "1.4", "1.7"], "2.2": ["1.1", "1.5", "1.6"],
    "2.3": ["1.4", "1.7", "1.3"], "2.4": ["1.6", "1.7", "1.4", "1.2"],
    "2.5": ["1.5", "1.4", "1.6", "1.7"], "2.6": ["1.3", "1.5"],
    "2.7": ["1.1", "1.5", "1.6", "1.7"]
  }'::jsonb;
  v_p1 public.profiles%rowtype;
  v_p2 public.profiles%rowtype;
  v_a integer := 0;
  v_p integer := 0;
  v_score double precision;
  v_interpretation text;
  rec record;
  comp text;
  status_other text;
begin
  select * into v_p1 from public.profiles where compatibility_code = trim(p_code1);
  if not found then raise exception 'Коды не найдены'; end if;
  select * into v_p2 from public.profiles where compatibility_code = trim(p_code2);
  if not found then raise exception 'Коды не найдены'; end if;

  if v_p1.archetype_scores is null or v_p2.archetype_scores is null then
    raise exception 'Коды не найдены';
  end if;

  -- Активные архетипы первого против комплементарных статусов второго
  for rec in select key, value::integer as score from jsonb_each_text(v_p1.archetype_scores)
  loop
    if public.archetype_status(rec.score) = 'A' then
      for comp in select jsonb_array_elements_text(coalesce(complementarity -> rec.key, '[]'::jsonb))
      loop
        status_other := public.archetype_status(coalesce((v_p2.archetype_scores ->> comp)::integer, 0));
        if status_other in ('A', 'M') then v_a := v_a + 1;
        elsif status_other = 'P' then v_p := v_p + 1;
        end if;
      end loop;
    end if;
  end loop;

  -- И наоборот
  for rec in select key, value::integer as score from jsonb_each_text(v_p2.archetype_scores)
  loop
    if public.archetype_status(rec.score) = 'A' then
      for comp in select jsonb_array_elements_text(coalesce(complementarity -> rec.key, '[]'::jsonb))
      loop
        status_other := public.archetype_status(coalesce((v_p1.archetype_scores ->> comp)::integer, 0));
        if status_other in ('A', 'M') then v_a := v_a + 1;
        elsif status_other = 'P' then v_p := v_p + 1;
        end if;
      end loop;
    end if;
  end loop;

  if v_a = 7 and v_p = 0 then v_interpretation := 'Максимальная прочность союза';
  elsif v_a = 0 and v_p = 7 then v_interpretation := 'Минимальная прочность (развал)';
  elsif v_p > 0 and v_a > v_p then v_interpretation := 'База есть, но есть очаги конфликтов';
  elsif v_a < v_p then v_interpretation := 'Союз временный (против больше чем за)';
  else v_interpretation := 'Средняя совместимость';
  end if;

  if v_a >= 3 then
    v_interpretation := v_interpretation || '. Отношения имеют тенденцию к сохранению';
  end if;

  if v_a + v_p > 0 then
    v_score := round((v_a::numeric / (v_a + v_p)) * 100, 1);
  else
    v_score := 50.0;
  end if;

  insert into public.couples (user1_code, user2_code, compatibility_index, a_count, p_count, score, interpretation)
  values (trim(p_code1), trim(p_code2), v_a || '/' || v_p, v_a, v_p, v_score, v_interpretation);

  return jsonb_build_object(
    'user1', jsonb_build_object('login', v_p1.login, 'code', trim(p_code1)),
    'user2', jsonb_build_object('login', v_p2.login, 'code', trim(p_code2)),
    'index', v_a || '/' || v_p,
    'A_count', v_a,
    'P_count', v_p,
    'score', v_score,
    'interpretation', v_interpretation
  );
end;
$$;

-- ============================================================
-- 6. АДМИН-ФУНКЦИИ
-- ============================================================

create or replace function public.admin_set_role(p_user_id uuid, p_role text)
returns void
language plpgsql volatile security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Доступ запрещен';
  end if;
  if p_role not in ('admin', 'user') then
    raise exception 'Роль: ''admin'' или ''user''';
  end if;
  update public.profiles set role = p_role where id = p_user_id;
end;
$$;

create or replace function public.admin_delete_user(p_user_id uuid)
returns void
language plpgsql volatile security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Доступ запрещен';
  end if;
  if p_user_id = auth.uid() then
    raise exception 'Нельзя удалить себя';
  end if;
  -- Каскадом удалятся профиль, результаты, ответы и комментарии
  delete from auth.users where id = p_user_id;
end;
$$;

-- ============================================================
-- 7. RLS-ПОЛИТИКИ
-- ============================================================

alter table public.profiles enable row level security;
alter table public.archetypes enable row level security;
alter table public.questions enable row level security;
alter table public.answers enable row level security;
alter table public.test_results enable row level security;
alter table public.consultations enable row level security;
alter table public.couples enable row level security;
alter table public.tests enable row level security;
alter table public.test_questions enable row level security;
alter table public.answer_options enable row level security;
alter table public.comments enable row level security;

-- Профили: свой профиль или админ; запись только через функции/триггер
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
  for select using (id = auth.uid() or public.is_admin());

-- Справочники: чтение всем, запись — админ
drop policy if exists archetypes_select on public.archetypes;
create policy archetypes_select on public.archetypes for select using (true);
drop policy if exists archetypes_admin_write on public.archetypes;
create policy archetypes_admin_write on public.archetypes
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists questions_select on public.questions;
create policy questions_select on public.questions for select using (true);
drop policy if exists questions_admin_write on public.questions;
create policy questions_admin_write on public.questions
  for all using (public.is_admin()) with check (public.is_admin());

-- Журнал ответов: смотрит только админ (запись идёт из security definer функции)
drop policy if exists answers_admin_select on public.answers;
create policy answers_admin_select on public.answers
  for select using (public.is_admin());

-- Результаты: свои или админ
drop policy if exists test_results_select on public.test_results;
create policy test_results_select on public.test_results
  for select using (user_id = auth.uid() or public.is_admin());
drop policy if exists test_results_admin_delete on public.test_results;
create policy test_results_admin_delete on public.test_results
  for delete using (public.is_admin());

-- Заявки: оставить может любой (в т.ч. неавторизованный), читает/меняет админ
drop policy if exists consultations_insert on public.consultations;
create policy consultations_insert on public.consultations
  for insert with check (true);
drop policy if exists consultations_admin_select on public.consultations;
create policy consultations_admin_select on public.consultations
  for select using (public.is_admin());
drop policy if exists consultations_admin_update on public.consultations;
create policy consultations_admin_update on public.consultations
  for update using (public.is_admin()) with check (public.is_admin());

-- Журнал совместимости: только админ (запись из security definer функции)
drop policy if exists couples_admin_select on public.couples;
create policy couples_admin_select on public.couples
  for select using (public.is_admin());

-- Конструктор тестов: чтение всем, запись — админ
drop policy if exists tests_select on public.tests;
create policy tests_select on public.tests for select using (true);
drop policy if exists tests_admin_write on public.tests;
create policy tests_admin_write on public.tests
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists test_questions_select on public.test_questions;
create policy test_questions_select on public.test_questions for select using (true);
drop policy if exists test_questions_admin_write on public.test_questions;
create policy test_questions_admin_write on public.test_questions
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists answer_options_select on public.answer_options;
create policy answer_options_select on public.answer_options for select using (true);
drop policy if exists answer_options_admin_write on public.answer_options;
create policy answer_options_admin_write on public.answer_options
  for all using (public.is_admin()) with check (public.is_admin());

-- Комментарии
drop policy if exists comments_select on public.comments;
create policy comments_select on public.comments for select using (true);
drop policy if exists comments_insert on public.comments;
create policy comments_insert on public.comments
  for insert with check (user_id = auth.uid());
drop policy if exists comments_update on public.comments;
create policy comments_update on public.comments
  for update using (user_id = auth.uid() or public.is_admin());
drop policy if exists comments_delete on public.comments;
create policy comments_delete on public.comments
  for delete using (user_id = auth.uid() or public.is_admin());

-- ============================================================
-- 8. СИД: архетипы
-- ============================================================

insert into public.archetypes (code, name, color, chakra, description, strengths, weaknesses) values
  -- Женские архетипы
  ('2.1', 'Ксения (Сестра/Артемида)', '#4169E1', 6, 'Архетип сестры/охотницы. Независимая, целеустремленная.', 'Независимость, целеустремленность', 'Может быть отстраненной'),
  ('2.2', 'Кира (Стратег/Афина)', '#8B00FF', 7, 'Архетип стратега. Рациональная, умная.', 'Мудрость, стратегическое мышление', 'Может быть холодной'),
  ('2.3', 'Катерина (Хранительница/Гестия)', '#87CEEB', 5, 'Архетип хранительницы. Создаёт уют.', 'Спокойствие, уют, мудрость', 'Может быть замкнутой'),
  ('2.4', 'Карина (Возлюбленная/Афродита)', '#FFA500', 2, 'Архетип любви и красоты.', 'Чувственность, творчество', 'Может быть эмоциональной'),
  ('2.5', 'Клара (Мать/Деметра)', '#FF0000', 1, 'Архетип матери. Заботливая, тёплая.', 'Заботливость, доброта, нежность', 'Может растворяться в детях'),
  ('2.6', 'Кристина (Дочь/Персефона)', '#008000', 4, 'Архетип дочери. Мягкая, адаптивная.', 'Гибкость, адаптивность', 'Может быть зависимой'),
  ('2.7', 'Каллерия (Жена/Гера)', '#FFD700', 3, 'Архетип жены. Верная, ориентирована на семью.', 'Верность, преданность', 'Может быть зависимой от партнёра'),
  -- Мужские архетипы
  ('1.1', 'Константин (Правитель/Зевс)', '#4B0082', null, 'Архетип правителя. Уверенный, лидер.', 'Лидерство, ответственность', 'Не заботится о чувствах'),
  ('1.2', 'Кирилл (Эмоциональный/Посейдон)', '#0000FF', null, 'Архетип эмоционального. Яркие чувства.', 'Эмоциональность, глубина', 'Нестабильность'),
  ('1.3', 'Клемент (Потусторонний/Гадес)', '#2F4F4F', null, 'Архетип потустороннего. Погружён в себя.', 'Интуиция, глубина', 'Сложно адаптироваться'),
  ('1.4', 'Кузьма (Умный/Гермес)', '#FFD700', null, 'Архетип путника. Постоянно в движении.', 'Гибкость, ум', 'Непостоянство'),
  ('1.5', 'Кондратий (Гармоничный/Аполлон)', '#FF6347', null, 'Архетип гармоничного. Любит точность.', 'Дипломатичность, логика', 'Не хватает чувств'),
  ('1.6', 'Кристиан (Ранимый/Гефест)', '#708090', null, 'Архетип творца. Чувствительный.', 'Творчество, глубина', 'Замкнутость'),
  ('1.7', 'Клим (Воинственный/Арес)', '#8B0000', null, 'Архетип воина. Эмоциональный, импульсивный.', 'Энергия, страсть', 'Импульсивность')
on conflict (code) do update set
  name = excluded.name,
  color = excluded.color,
  chakra = excluded.chakra,
  description = excluded.description,
  strengths = excluded.strengths,
  weaknesses = excluded.weaknesses;

-- ============================================================
-- 9. СИД: вопросы (каждый вопрос — свой класс-архетип)
-- ============================================================

-- Заполняем только если вопросов ещё нет
do $$
begin
  if exists (select 1 from public.questions) then
    return;
  end if;

  -- Женские вопросы (35)
  insert into public.questions (gender_type, text, archetype_code, order_index) values
    ('female', 'Мне нравится быть в образе мамы, такой теплой и заботливой. Я всегда знала, что стану хорошей матерью.', '2.5', 1),
    ('female', 'Я с детства любила мечтать, я путешествовала в своих мирах.', '2.6', 2),
    ('female', 'Я всегда чувствовала себя как будто в ответе за взрослых. Они были как будто дети, а я — взрослая.', '2.5', 3),
    ('female', 'Девочкой меня называли «пацанкой». Я была на равных с мальчишками.', '2.1', 4),
    ('female', 'Когда я была маленькой, порой родители бурно ссорились, а я сидела в своей комнате и боялась.', '2.3', 5),
    ('female', 'Я с детства планировала свою свадьбу. Мне хотелось красивой свадьбы, белого платья.', '2.7', 6),
    ('female', 'Тема секса всегда немного запретная, в моей семье об этом не принято говорить.', '2.4', 7),
    ('female', 'Глава семьи – отец, он опора и сила, он принимает решения.', '2.2', 8),
    ('female', 'С детства споры мамы и папы для меня были однозначны — папа всегда прав.', '2.2', 9),
    ('female', 'Чтобы меня убедить, нужно быть логичным. Мне нужны доказательства.', '2.6', 10),
    ('female', 'Смотря на родителей. Мне всегда хотелось быть почему-то как папа.', '2.2', 11),
    ('female', 'Я верю в судьбу, предопределенность. Всё, что должно случиться — случится.', '2.3', 12),
    ('female', 'Принять решение одной – сравни эгоизму. Нужно советоваться с близкими.', '2.6', 13),
    ('female', 'И в детстве и сейчас у меня много друзей. Я люблю общаться.', '2.1', 14),
    ('female', 'Когда домочадцев нет дома, наступает мое волшебное время — я наслаждаюсь уединением.', '2.3', 15),
    ('female', 'Красивые вещи меня гипнотизируют. Я могу долго смотреть на красивое.', '2.6', 16),
    ('female', 'Преданность и верность - главные ценности в отношениях.', '2.7', 17),
    ('female', 'Выбирая партнера я смотрю на его мужественность. Мне нужен сильный мужчина.', '2.2', 18),
    ('female', 'Мужчина ведом, лучше всегда будь на страже. Нельзя полностью доверяться.', '2.7', 19),
    ('female', 'Синоним «партнера» – скорее «друг». Мы как друзья.', '2.1', 20),
    ('female', 'Когда я готовлю, я словно колдую. Я получаю удовольствие от процесса.', '2.5', 21),
    ('female', 'Одно из приятных и важных для меня ощущений – ощущение своего тела.', '2.4', 22),
    ('female', 'Огонь - это таинство. Я могу бесконечно смотреть на огонь.', '2.3', 23),
    ('female', 'Себя и близких я в обиду не дам. Я всегда защищу своих.', '2.1', 24),
    ('female', 'Главные чувства в отношениях – тепло и забота. Мне важно чувствовать заботу.', '2.6', 25),
    ('female', 'Вечеринки, тусовочки, шумные посиделки – это все «мое». Я люблю компанию.', '2.1', 26),
    ('female', 'Женщину должен обеспечивать ее мужчина. Это правильно.', '2.7', 27),
    ('female', 'Забавно, но из своего опыта я поняла, что мужчина тот же мальчик, только большой.', '2.5', 28),
    ('female', 'У мужчин есть своя особая сексуальность, которую я чувствую.', '2.4', 29),
    ('female', 'Если мой партнер в сексе получил удовольствие, то я получаю большее.', '2.5', 30),
    ('female', 'Мое отношение к сексу очень простое – это не более чем физиологическая потребность.', '2.2', 31),
    ('female', 'Когда я вступаю в близкие отношения, я не мыслю их без секса.', '2.4', 32),
    ('female', 'Таинство секса – это подарок мой миру. Это нечто большее чем физика.', '2.3', 33),
    ('female', 'С сексом все просто – это супружеский долг. Это обязанность в браке.', '2.7', 34),
    ('female', 'Я не разделяю любовь и секс. Это неразделимые вещи.', '2.4', 35);

  -- Мужские вопросы (35, ровно по 5 на каждый из 7 классов).
  -- В старой версии распределение было сломано: у 1.2 не было ни одного
  -- вопроса, у 1.6 — только два. Набор дописан и сбалансирован.
  insert into public.questions (gender_type, text, archetype_code, order_index) values
    ('male', 'Мне нравится быть в образе отца, такого заботливого и сильного. Я всегда знал, что стану хорошим отцом.', '1.5', 1),
    ('male', 'Я с детства любил мечтать, я путешествовал в своих мирах.', '1.3', 2),
    ('male', 'Я всегда чувствовал себя как будто в ответе за взрослых. Они были как дети, а я — взрослый.', '1.5', 3),
    ('male', 'Мои чувства как стихия: то штиль, то шторм. Эмоции могут накрыть меня с головой.', '1.2', 4),
    ('male', 'Когда я был маленьким, порой родители бурно ссорились, а я сидел в своей комнате и боялся.', '1.6', 5),
    ('male', 'В любой компании я естественно становлюсь главным. Мне привычно брать ответственность и управлять.', '1.1', 6),
    ('male', 'Тема секса всегда немного запретная, в моей семье об этом не принято говорить.', '1.6', 7),
    ('male', 'Глава семьи – отец, он опора и сила, он принимает решения.', '1.1', 8),
    ('male', 'С детства споры мамы и папы для меня были однозначны — папа всегда прав.', '1.1', 9),
    ('male', 'Чтобы меня убедить, нужно быть логичным. Мне нужны доказательства.', '1.5', 10),
    ('male', 'Смотря на родителей, мне всегда хотелось быть почему-то как мама.', '1.6', 11),
    ('male', 'Я верю в судьбу, предопределенность. Всё, что должно случиться — случится.', '1.3', 12),
    ('male', 'Если меня задели, я вспыхиваю мгновенно, а потом ещё долго переживаю всё внутри.', '1.2', 13),
    ('male', 'И в детстве и сейчас у меня много друзей. Я люблю общаться.', '1.4', 14),
    ('male', 'Когда домочадцев нет дома, наступает мое волшебное время — я наслаждаюсь уединением.', '1.3', 15),
    ('male', 'Красивые вещи меня гипнотизируют. Я могу долго смотреть на красивое.', '1.6', 16),
    ('male', 'Преданность и верность - главные ценности в отношениях.', '1.7', 17),
    ('male', 'Выбирая партнершу я смотрю на её женственность. Мне нужна женственная женщина.', '1.1', 18),
    ('male', 'Женщина ведомa, лучше всегда будь на страже. Нельзя полностью доверяться.', '1.7', 19),
    ('male', 'Синоним «партнерши» – скорее «подруга». Мы как друзья.', '1.4', 20),
    ('male', 'Когда я готовлю, я словно колдую. Я получаю удовольствие от процесса.', '1.6', 21),
    ('male', 'Сначала я чувствую, потом думаю. Эмоции для меня важнее сухих доводов.', '1.2', 22),
    ('male', 'Огонь - это таинство. Я могу бесконечно смотреть на огонь.', '1.3', 23),
    ('male', 'Себя и близких я в обиду не дам. Я всегда защищу своих.', '1.7', 24),
    ('male', 'Мне важны порядок и точность: во всём люблю ясность, меру и гармонию.', '1.5', 25),
    ('male', 'Вечеринки, тусовочки, шумные посиделки – это все «мое». Я люблю компанию.', '1.4', 26),
    ('male', 'Мужчина должен обеспечивать свою семью. Это правильно.', '1.7', 27),
    ('male', 'Мне быстро наскучивает сидеть на месте: люблю перемены, дороги и новые впечатления.', '1.4', 28),
    ('male', 'У женщин есть своя особая женственность, которую я чувствую.', '1.4', 29),
    ('male', 'Если моя партнерша в сексе получила удовольствие, то я получаю большее.', '1.5', 30),
    ('male', 'Мое отношение к сексу очень простое – это не более чем физиологическая потребность.', '1.1', 31),
    ('male', 'Когда я вступаю в близкие отношения, я не мыслю их без секса.', '1.2', 32),
    ('male', 'Таинство секса – это подарок мой миру. Это нечто большее чем физика.', '1.3', 33),
    ('male', 'С сексом все просто – это супружеский долг. Это обязанность в браке.', '1.7', 34),
    ('male', 'Я не разделяю любовь и секс. Это неразделимые вещи.', '1.2', 35);
end;
$$;

-- ============================================================
-- 10. ПРАВА НА ФУНКЦИИ
-- ============================================================

grant execute on function public.login_exists(text) to anon, authenticated;
grant execute on function public.get_profile_by_code(text) to anon, authenticated;
grant execute on function public.check_compatibility(text, text) to anon, authenticated;
grant execute on function public.complete_test(text, jsonb, text) to authenticated;
grant execute on function public.save_results_to_account(text) to authenticated;
grant execute on function public.admin_set_role(uuid, text) to authenticated;
grant execute on function public.admin_delete_user(uuid) to authenticated;

-- ============================================================
-- ГОТОВО.
-- После выполнения схемы:
-- 1. В Supabase: Authentication -> Providers -> Email -> отключите "Confirm email".
-- 2. Зарегистрируйтесь на сайте, затем назначьте себя админом:
--    update public.profiles set role = 'admin' where login = 'ВАШ_ЛОГИН';
-- ============================================================
